language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.2
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x scripts
script:
 - ./dotnet-build.sh
notifications:
  email:
    on_success: never
    on_failure: always