language: csharp
dist: trusty
sudo: required
dist: xenial
mono: none
dotnet: 2.2
branches:
  only:
    - master
    - develop
script:
 - dotnet restore
 - dotnet build
 - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
 - docker build -f ./DevOps.Api/Dockerfile -t devopsapi:dev ./DevOps.Api --no-cache
 - docker tag devopsapi:dev $DOCKER_USERNAME/devops:dev
 - docker push $DOCKER_USERNAME/devops:dev


notifications:
  email:
    on_success: never
    on_failure: always