language: csharp
dist: trusty
sudo: required
dist: xenial
mono: none
dotnet: 2.2
branches:
  only:
    - master
    - develop
script:
 - dotnet restore
 - dotnet build
notifications:
  email:
    on_success: never
    on_failure: always